/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006857',
        'primary-container': '#00846e',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffa',
        'primary-fixed': '#7cf8da',
        'primary-fixed-dim': '#5ddbbe',
        secondary: '#ae2f34',
        'secondary-container': '#ff6b6b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6d0010',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b0',
        tertiary: '#005bb3',
        'tertiary-container': '#1a73da',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fefcff',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-fixed-dim': '#a9c7ff',
        surface: '#f8fafb',
        'surface-bright': '#f8fafb',
        'surface-dim': '#d8dadb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f5',
        'surface-container': '#eceeef',
        'surface-container-high': '#e6e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#006b59',
        'on-surface': '#191c1d',
        'on-surface-variant': '#3d4945',
        'on-background': '#191c1d',
        background: '#f8fafb',
        outline: '#6d7a75',
        'outline-variant': '#bccac4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#eff1f2',
        'inverse-primary': '#5ddbbe',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

